### ISSUE TITLE
Inspecting normal System.IO.Streams

### ISSUE THREAD

**Issue by reinux** [MediatedCommunications/Mime-Detective#14]
I'm seeing an overload of `ContentInspector.Inspect` that takes an `IEnumerable<byte>` or a `byte []`, but I'm not seeing one that takes a `System.IO.Stream`. This seems suboptimal.

Is there a way to get a byte enumerable from a stream, or do I need to write one manually?

**Comment by TonyValenti** [comment]
This is a great idea!  I'll push an update tomorrow that adds that as a feature.

**Comment by reinux** [comment]
Thanks!

Internally, does it need to read the whole file, or is it able to decide most of the time from the first few bytes?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TonyValenti** [comment]
Hi @reinux .  I just published an update with extension methods that will do as you ask.

When you request a detection, it will use all the ```byte```s you provide it to assist in making its determination.  For small streams, loading a few MB into memory is no big deal, but you likely wouldn't want to read a whole 2GB into memory!

To assist with that, the extension methods use the ```ContentReader``` class and will default to ```ContentReader.Default``` if none is provided.  ```ContentReader.Default``` will read, at most, 10MB of data from a stream.

**Comment by reinux** [comment]
Thanks!

Just curious, what is it doing that requires it to look at all the bytes, when the first few bytes typically contains the magic word?

**Comment by reinux** [comment]
Got it, thanks 👍
