### ISSUE TITLE
Upgrade path from the previous nuget owner?

### ISSUE THREAD

**Issue by sandrock** [MediatedCommunications/Mime-Detective#17]
I am quite surprised the owner of the [nuget package](https://www.nuget.org/packages/Mime-Detective) has changed. 

The library and license have changed. 

Can you state what changes? And how to update?

If the library is not the same, why not use a different nuget name?

This change looks very suspicious.

---

Repo history:  
Original repo was https://github.com/Muraad/Mime-Detective  
Nuget  0.0.6-beta5 pointed to https://github.com/clarkis117/Mime-Detective.git (repo does not exist any more)     
clarkis's repo seem to have moved to https://github.com/TonyValenti/Mime-Detective-clarkis117    
Is TonyValenti a member of <https://github.com/MediatedCommunications>?

**Comment by TonyValenti** [comment]
Hi @sandrock !
The previous package had not been maintained and there are newer/better technologies to do much better detection. The original owner allowed me to take over the package and modernize it.

**Comment by TonyValenti** [comment]
In terms of upgrade path, it is a major version upgrade (complete rewrite!) and should be treated as such.

**Comment by sandrock** [comment]
> The previous package had not been maintained and there are newer/better technologies to do much better detection. The original owner allowed me to take over the package and modernize it.

Thank you for this information.

> In terms of upgrade path, it is a major version upgrade (complete rewrite!) and should be treated as such.

I see the new project has 3 data sources. Which one is the closest equivalent to the previous project?

**Comment by TonyValenti** [comment]
Just plain old Mime-Detective without the extra definition packs.

**Comment by sandrock** [comment]
Thanks.
