### ISSUE TITLE
How to acquire a license for Condensed/Exhaustive definitions?

### ISSUE THREAD

**Issue by sandrock** [MediatedCommunications/Mime-Detective#18]
The README states:

> It is derived from the publicly available [TrID file signatures](https://mark0.net/soft-tridnet-e.html)
which may be used for personal/non-commercial use (free) or with a [paid commercial license](https://mark0.net) (usually around 300€).

The website does not state any precise licensing models for TrID. 

>  TrID is free for personal / non commercial use.  (the end)

Is MediatedCommunications affiliated with mark0?

**Comment by sandrock** [comment]
This [forum post](https://mark0.net/forum/index.php?topic=180.msg1023#msg1023) says:

> Sure. Send me a mail (see the [Contacts](http://mark0.net/contacts.html) page) and we can discuss.

I am going to try that.

**Comment by TonyValenti** [comment]
Also, just so you know, only the additional definitions require a license trid.  The built in ones do not rely on Trid and are free for all.
