### ISSUE TITLE
some missing types

### ISSUE THREAD

**Issue by dbmuller** [MediatedCommunications/Mime-Detective#19]
Hi, is it possible to add a few less common and new types to some of the lists?

.mpp
.webp
.HEIF
.HEVC

**Comment by mrUlrik** [comment]
I second the addition of webp.

**Comment by TonyValenti** [comment]
Do you need it in exhaustive or the basic one?  If exhaustive, can you submit an addition to TRID?  One it is accepted then we can ingest their latest definitions.

**Comment by mrUlrik** [comment]
It appears it may already be on the list? https://mark0.net/soft-trid-deflist-w.html

WebP is rapidly getting attention from web developers and is widely accepted in modern browsers.

**Comment by TonyValenti** [comment]
I those definitions are already on the exhaustive list if they are listed in trid.
