### ISSUE TITLE
The GL Transmission Format MIME Type is incorrect

### ISSUE THREAD

**Issue by B3zaleel** [MediatedCommunications/Mime-Detective#22]
The binary GL Transmission Format with a glb extension should have `model/gltf-binary` as its MIME type rather than `application/octet-stream`. Consequently, the MIME type of the non-binary GL Transmission Format with a gltf extension should be `model/gltf+json`.

**Comment by TonyValenti** [comment]
Hi @B3zaleel - can you submit these definitions to mark0.net so they can be incorporated into the next update?

**Comment by B3zaleel** [comment]
Hi @TonyValenti. I've submitted the definitions to mark0.net and the definitions have been updated.

**Comment by TonyValenti** [comment]
I just published a package that incorporates the latest updates.  Make sure youve paid Mark0 if you're using Exhaustive in a commercial environment.
