### ISSUE TITLE
README issue

### ISSUE THREAD

**Issue by jchristn** [MediatedCommunications/Mime-Detective#26]
The two examples both have the same issue:
```
using MimeDetective;
var Inspector = new ContentInspectorBuilder() {
    Definitions = Definitions.Default.All()
}.Build();
```
```Definitions.Default.All()``` needs to be fully qualified as ```MimeDetective.Definitions.Default.All()```

**Comment by TonyValenti** [comment]
Thanks!  I'll fix it.
