### ISSUE TITLE
Mime Detective does not recognise plain text files

### ISSUE THREAD

**Issue by CSL-SSG** [MediatedCommunications/Mime-Detective#33]
The Mime Detective returns and empty list when running ContentInspector.Inspect on a text/plain file.

I see there was a ticket opened for this before: https://github.com/MediatedCommunications/Mime-Detective/issues/9 however the issue was not resolved, instead alternative text files were proposed.

Is there any solution to get this working with plain text files?

Thank you

Note: I'm using it from the .NET nugget package: https://www.nuget.org/packages/Mime-Detective

**Comment by TonyValenti** [comment]
Please see https://github.com/MediatedCommunications/Mime-Detective#how-does-it-work for information regarding how MD works and limitations regarding non-binary files.
