### ISSUE TITLE
big PPTX file(s) identified as zip/zip/pg

### ISSUE THREAD

**Issue by cz35iek** [MediatedCommunications/Mime-Detective#35]
Hi,

We are using Mime-Detective library version 23.10.1, with Exhaustive Definitions. We are happy with the coverage of files recognized by library, but lately we've observed some issue with pptx file(s) recognition. 

example here -> [12 MB.pptx](https://github.com/MediatedCommunications/Mime-Detective/files/13298152/12.MB.pptx

Here is recognition result ->

```
zip /// 4027 Points /// Open Packaging Conventions container
zip /// 4000 Points /// ZIP compressed archive
pg /// 1000 Points /// PrintFox/Pagefox bitmap (640x800)
```

this is our code sample, how we use library ->

```
_inspector = new ContentInspectorBuilder()
{
    Definitions = new MimeDetective.Definitions.ExhaustiveBuilder()
    {
        UsageType = MimeDetective.Definitions.Licensing.UsageType.CommercialPaid
    }.Build()
}.Build();
)


...

var results = _inspector.Inspect(stream, true);
```

For smaller (other) files the library is able to recognize pptx files correctly. Can we do something on our side, apply some workaround or this is related to detector library and we need to wait for the updates?

BR,
Dawid

**Comment by TonyValenti** [comment]
Hi Dawid,
This is caused because PPTXs are actually ZIP files underneath.  In fact, as a test, take your PPTX, give it a .ZIP extension, and then open it in Windows.  Because PPTXs are a zip subtype, sometimes detecting can be tricky and can mis-identify a file as the parent type.
