### ISSUE TITLE
Yaml file identified as EML file

### ISSUE THREAD

**Issue by bsinghal-copperleaf** [MediatedCommunications/Mime-Detective#37]
The file below gets marked as an EML file because the word "FROM" appears in the text. The word from obviously comes way after the starting few bytes and so not sure why it is being marked as an EML file.

To reproduce, just download the attached file. Change it's extension to .yaml and try to run the inspection on it with all the default definitions loaded in.

NOTE : You might not even need to change the extension but I had to for uploading it to GitHub

[recipe.txt](https://github.com/MediatedCommunications/Mime-Detective/files/14938419/recipe.txt)

**Comment by bsinghal-copperleaf** [comment]
Code:

```CSharp
_textInspector = new ContentInspectorBuilder
{
    Definitions = MimeDetective.Definitions.Default.All()
}.Build();
inspectionResult = _textInspector.Inspect(filePath);
```

The result was ```/// eml 4 point```.

**Comment by TonyValenti** [comment]
I'll address types/subtypes in an upcoming article.
