### ISSUE TITLE
JSON detection

### ISSUE THREAD

**Issue by mikoskinen** [MediatedCommunications/Mime-Detective#38]
Thank you for a nice library.

I've been testing different file types and overall things look good but I haven't been able to get Mime Detective to detect JSON files (based on the byte array). Is this something that should/could be supported?

**Comment by TonyValenti** [comment]
Not likely. While we all know what Json looks like, it is a text-based format and does not have any identifying byte markers that mime detective could use. 

You would simply need to write a function that tries to parse the file as Jason and returns false crashes.

**Comment by TonyValenti** [comment]
I'll address types/subtypes in an upcoming article.
