### ISSUE TITLE
WebP detection

### ISSUE THREAD

**Issue by jgwconsulting** [MediatedCommunications/Mime-Detective#39]
Thanks for the great library, @TonyValenti :)

Some info for anyone wanting to detect WebP without the overhead of all the additional definitions from the exhaustive package: this lib makes it very easy to add your own definitions, including webp. Gist here: 

https://gist.github.com/jgwconsulting/856a31ddfaef90df9f33fb57b6854a4d

**Comment by TonyValenti** [comment]
Can I incorporate that into the core?

**Comment by TonyValenti** [comment]
@jgwconsulting - I just pushed an update that contains this definition.
