### ISSUE TITLE
"CommercialFree" is not allowed

### ISSUE THREAD

**Issue by AlexSchuetz** [MediatedCommunications/Mime-Detective#6]
If a UsageType "CommercialFree" is supported, this shouldn't cause a runtime-exception. Instead I would have expected a reduced set of supported definitions.

If it is not planed to support any definition with "CommercialFree" this usage type should be removed. If there was no usage type "CommercialFree" I would have known from the start, that this library is no option.

**Comment by TonyValenti** [comment]
Hi @AlexSchuetz - 
What definition pack are you using?  Different definition packs support different license types.

**Comment by AlexSchuetz** [comment]
I used Exhausive, since it was the first one I found.
But the issue still remains the same for me: if there is a usage type it should be usable. Otherwise it shouldn't be there.

**Comment by TonyValenti** [comment]
Hi Alex,
I just pushed an update that adjusts a few things in this regard. Specifically, a better error message is shown showing the different valid usage types.
