### ISSUE TITLE
Plain old text files?

### ISSUE THREAD

**Issue by jbrockerville** [MediatedCommunications/Mime-Detective#9]
I don't seem to be able to get MD to detect "plain old text" files. I see the various magic strings that are looked for in `Default.FileTypes.Text.cs`, but a plain old text file saved from, say Notepad on Windows, does not have a magic string. I do not have the file extension. What could I do here?

**Comment by jbrockerville** [comment]
Or more specifically, [Windows-1252 encoding](https://en.wikipedia.org/wiki/Windows-1252).

**Comment by TonyValenti** [comment]
Hi @jbrockerville -
How do you propose determining that match?  In your situation, I'd recommend maybe defaulting to that based on your data set.

**Comment by jbrockerville** [comment]
Hi @TonyValenti 
Thanks for replying. I'm not proposing solution. I'm unsure of how to proceed. Your suggestion is a good one, unfortunately, my data set is "anything". Could be a zip, exe, image, doc, txt, etc. Anything.

**Comment by TonyValenti** [comment]
what's your phone number?  I'll give you a call.  Or you can call me.  402-509-9270.  I have a few ideas.

**Comment by danielbichuetti** [comment]
Hi guys,

I've been testing MD these days. I found that if using UTF8 without BOM it won't detected the txt file. But if you change for using BOM it will.

Also there is one issue with json files being detected with 1000 points as ini.

**Comment by CSL-SSG** [comment]
Was this issue resolved? As far as I can tell the detection of plain text files still fails. There are some alternative files mentioned here that work, however as far as plain text files goes, the issue still remains

**Comment by TonyValenti** [comment]
@CSL-SSG -
Please take a look at https://github.com/MediatedCommunications/Mime-Detective#how-does-it-work for information RE how MD works and limitations regarding non-binary files.
